#!/bin/sh
# dmenu_path | dmenu -b -fn "-*-dejavu sans mono-medium-r-normal--*-*-*-*-*-*-iso1046-*" -nb "#000000" -nf "#ffffff" -sb "#ffffff" -sf "#000000" "$@" | ${SHELL:-"/bin/sh"} &
#dmenu_path | dmenu -b -fn "-*-courier-medium-r-normal--*_*-*-*-*-*-iso10646-*" -nb "#000000" -nf "#ffffff" -sb "#ffffff" -sf "#000000" "$@" | ${SHELL:-"/bin/sh"} &
dmenu_path | dmenu -fn "-xos4-terminus-medium-r-*-*-14-*" -nb "#000000" -nf "#ffffff" -sb "#ffffff" -sf "#000000" "$@" | ${SHELL:-"/bin/sh"} &
