#!/bin/bash
installation="$HOME/.config/installation.json"
tmp=$(mktemp)
cat "$installation" | jq -e '.aur | index( "'${1}'" )' > /dev/null || (cat "$installation" | jq -e ".aur += [\"${1}\"]" > "$tmp" && mv $tmp $installation)

